### ISSUE TITLE
Tasks for Next Week (11/15) / Next Milestone

### ISSUE THREAD

**Issue by ebeshero** [zteyssier/JamesBondMCI#7]
## Web work
- [x] Remember to push everything to GitHub
*You may need to delete files on the newtfire server in order to replace them if you do not "own"  the file on the webserver.*
- [x] fix the menu bar @CTrohoske01 
- [x] Make a logo @dpakulski42 
- [x] Work on wording for website pages @zteyssier and @dpakulski42 

## XML work

- [ ] Add attributes to intro songs and to screen plays for:   
 * love vs. revenge vs. ___? ____ (songs only) 
* male and female (both songs and screen plays) Each of you does this for each screenplay + songs you're working on.

- [x] Update the schema file to include attributes @CTrohoske01 

- [ ] LAST CALL!  Find missing screenplays if possible! Open an Issue here to list and link what screenplays you've located. @zteyssier @CTrohoske01 @dpakulski42 
- [ ] Screenplays up-conversion: START by converting ASCII to unicode (if your files have lots of weird characters in them for, say, apostrophes, quotation marks, punctuation marks.
   * Check out [Notepad++ on Windows](https://notepad-plus-plus.org/downloads/) 
   * OR, there are [online ASCII to Unicode converters ](https://onlineasciitools.com/convert-ascii-to-unicode) you can try like maybe this one. 

- [ ] Everyone finish up-converting screenplays! @zteyssier @dpakulski42 @CTrohoske01 
*Check in with Dr. B if you need help b/c the regex is not exactly easy*
- [ ] Investigate music scores and information about the theme music @zteyssier @CTrohoske01
