### ISSUE TITLE
New Task List for 12/11

### ISSUE THREAD

**Issue by zteyssier** [zteyssier/JamesBondMCI#8]
- [x] - SVG awareness of gender roles, m, f, t @CTrohoske01 

- [ ] - Finsih markup on existing screenplays within XML-Screenplays @CTrohoske01  

- [ ] - SVG on `@Keywords` @zteyssier 

- [ ] - Music Notation data, scene data, Orchestral Scores linked to website "Proof of Concept" @zteyssier 

- [ ] - SVG POV @dpakulski42 

- [ ] -  Consistent CSS @dpakulski42 

- [ ] - Javascript @dpakulski42 

- [ ] - **Write up on the Website: What did you learn, what were your sources like (links), what is next?** @zteyssier @dpakulski42 @CTrohoske01
